 CommonResources = { 
'Orders' : 'Заказы',
'Staff' : 'Персонал',
'Geography' : 'ГеоОбъекты',
'Production' : 'Производство',
'Administration' : 'Администрирование',
'Username' : 'Имя пользователя',
'Password' : 'Пароль',
'Remember_me' : 'Запомнить меня',
'Login' : 'Логин',
'Login_to_your_account' : 'Доступ к вашему аккаунту',
'Orders_Creation_System' : 'Система создания заказов',
'Page_Loading_Error' : 'Ошибка загрузки страницы',
'Save' : 'Сохранить',
'Actions' : 'Действия',
'User_Image' : 'Изображение пользователя',
'Upload' : 'Загрузить',
'Edit_User_Profile' : 'Редактирование профиля пользователя',
'Operations' : 'Операции',
'Edit' : 'Изм',
'Del' : 'Удал',
'Loading' : 'Загрузка...',
'Create' : 'Создать',
'Delete' : 'Удалить',
'Cancel' : 'Отменить',
'Edit_Order_Item' : 'Редактирование элемента заказа',
'New_Order_Item' : 'Создать элемент заказа',
'Price_Of_Single_Product' : 'Цена одного продукта',
'Common_Order_Item_Price' : 'Общая цена позиции в заказе',
'Total' : 'Всего',
'Displayed' : 'Отображено',
'Selected' : 'Выбрано',
'There_Are_Several_Validation_Errors' : 'Обнаружены ошибки валидации',
'Add' : 'Добавить',
'Category_Search' : 'Поиск категории',
'Description' : 'Описание',
'Image' : 'Изображение',
'Information' : 'Информация',
'Clear' : 'Очистить',
'Date_Create' : 'Дата создания',
'Date_Modify' : 'Дата изменения',
'Amount_Of_Categories' : 'Количество категорий',
'Amount_Of_Items' : 'Количество элементов',
'Search_Results_Is_Empty' : 'Результаты поиска пусты',
'Search' : 'Поиск',
'Main_Data' : 'Основные данные',
'Location' : 'Местонахождение',
'Flag_Of_Country' : 'Флаг страны',
'Upload_Flag' : 'Загрузить флаг',
'Delete_Selected' : 'Удалить выбранные',
'Clear_List' : 'Очистить список',
'Order_Data' : 'Данные заказа',
'OrderItems_Total' : 'Всего элементов заказа',
'Total_Buy_Price' : 'Общая цена покупки',
'Total_Sell_Price' : 'Общая цена продажи',
'Please_Choose_The_City' : 'Пожалуйста выберите город',
'Please_Choose_The_Country' : 'Пожалуйста выберите страну',
'Please_Choose_The_Region' : 'Пожалуйста выберите регион',
'Please_Choose_The_Street' : 'Пожалуйста выберите улицу',
'Please_Enter_The_Number' : 'Пожалуйста введите номер дома',
'Numbers_List_CommaSeparated' : 'Список номеров, разделенных запятой',
'Min' : 'Мин',
'Max' : 'Макс',
'Enter_The_Text' : 'Введите текст',
'Choose_The_Product_From_DropDown' : 'Пожалуйста выберите товар из выпадающего списка',
'Amount' : 'Количество',
'Login_Error' : 'Ошибка входа',
'Identifers' : 'Идентификаторы',
'Are_You_Really_Want_ToDelete_Selected_Record' : 'Вы действительно хотите удалить выбранную запись?',
'Are_You_Really_Want_ToDelete_Selected_Records' : 'Вы действительно желаете удалить выбранные записи?',
'Name' : 'Название',
'Please_Enter_At_Least_ThreeSymbols' : 'Введите как минимум три символа',
'Categories_List' : 'Список категорий',
'Edit_City' : 'Редактирование города',
'New_City' : 'Новый город',
'Choose_The_Region_From_DropDown' : 'Пожалуйста выберите регион из выпадающего списка',
'Please_Enter_The_City_Name_required' : 'Пожалуйста введите имя города (обязательно)',
'Population' : 'Население',
'Name_Of_Region' : 'Название региона',
'Please_Enter_At_Least_Three_Symbols' : 'Пожалуйста введите как минимум три символа',
'List_Of_Cities' : 'Список городов',
'Create_Client' : 'Создание клиента',
'Edit_Client' : 'Редактирование клиента',
'Common_Name' : 'Общее имя',
'Please_Enter_The_Common_Name_Required' : 'Введите общее имя (обязательно)',
'Full_Name' : 'Полное имя',
'Please_Enter_The_Full_Name_required' : 'Введите полное имя (обязательно)',
'Please_Enter_The_INN_required' : 'Введите полное имя (обязательно)',
'Enter_The_OGRN' : 'Введите полное имя (обязательно)',
'Enter_The_Country' : 'Выберите страну',
'Enter_The_Region' : 'Выберите регион',
'Enter_The_City' : 'Выберите город',
'Enter_The_Street' : 'Выберите улицу',
'Code' : 'Код',
'Edit_Country' : 'Редактирование страны',
'Create_Country' : 'Создание страны',
'English_Country_Name_required' : 'Введите название страны на английском языке (обязательно)',
'Russian_Country_Name_required' : 'Введите название страны на русском языке (обязательно)',
'Country_Code_required' : 'Код страны (обязательно)',
'Address' : 'Адрес',
'Clients_List' : 'Список клиентов',
'Countries_List' : 'Список стран',
'Edit_Employee' : 'Редактирование сотрудника',
'Create_Employee' : 'Создание сотрудника',
'_Required_' : ' (обязательно)',
'Please_Enter_The_Position_From_DropDown' : 'Пожалуйста выберите должность из выпадающего списка',
'Employees_List' : 'Список работников',
'Edit_House' : 'Редактирование дома',
'Create_House' : 'Создание дома',
'Enter_Building' : 'Введите корпус',
'Enter_PostalCode' : 'Введите индекс',
'Select_Street_From_Dropdown' : 'Выберите улицу из выпадающего списка',
'Houses_List' : 'Список домов',
'Positions_List' : 'Список должностей',
'Edit_Position' : 'Редактирование должности',
'Create_Position' : 'Создание должности',
'Edit_Product' : 'Редактирование товара',
'Create_Product' : 'Создание товара',
'Select_a_Category' : 'Выберите категорию',
'Products_List' : 'Список товаров',
'Edit_Region' : 'Редактирование региона',
'Create_Region' : 'Создание региона',
'Regions_List' : 'Список регионов',
'Edit_Role' : 'Редактирование региона',
'New_Role' : 'Новая роль',
'Edit_Street' : 'Редактирование улицы',
'New_Street' : 'Новая улица',
'Roles_list' : 'Список ролей',
'Select_a_City_From_Dropdown' : 'Пожалуйста выберите город из выпадающего списка',
'Streets_List' : 'Спиок улиц',
'Edit_User' : 'Редактирование пользователя',
'New_User' : 'Новый пользователь',
'Orders_List' : 'Список заказов',
'Edit_Order' : 'Редактирование заказа',
'Create_Order' : 'Создание заказа',
'Code_Will_be_generated_automatically' : 'Код будет сгенерирован автоматически',
'Please_select_a_client_from_dropdown' : 'Пожалуйста выберите заказчика из выпадающего списка'
 }