 var EntitiesResources = { 
'Order' : 'Заказ',
'Orders' : 'Заказы',
'Order_Code' : 'Код заказа',
'Order_OrderItems' : 'Элементы заказа',
'Order_Client' : 'Клиент заказа',
'Order_SellPrice' : 'Цена продажи заказа',
'Order_BuyPrice' : 'Цена покупки заказа',
'OrderItem' : 'Элемент заказа',
'OrderItems' : 'Элементы заказа',
'OrderItem_Product' : 'Товар в заказе',
'OrderItem_Order' : 'Элемент заказа',
'OrderItem_SellPrice' : 'Цена продажи товарной позиции',
'OrderItem_BuyPrice' : 'Цена покупки товарной позиции',
'Role' : 'Роль',
'Roles' : 'Роли',
'Role_Name' : 'Название роли',
'Role_Users' : 'Пользователи роли',
'Role_Permissions' : 'Разрешения роли',
'User' : 'Пользователь',
'Users' : 'Пользователи',
'User_Image' : 'Изображение пользователя',
'User_Name' : 'Имя пользователя',
'User_Email' : 'Email пользователя',
'User_Password' : 'Пароль',
'User_Roles' : 'Роли пользователя',
'City' : 'Город',
'Cities' : 'Города',
'City_Name' : 'Название города',
'City_Region' : 'Регион',
'City_Population' : 'Численность населения',
'City_Streets' : 'Улицы города',
'Country' : 'Страна',
'Countries' : 'Страны',
'Country_Code' : 'Код страны',
'Country_Name' : 'Название страны на английском',
'Country_RussianName' : 'Название страны на русском',
'Country_Flag' : 'Флаг страны',
'House' : 'Дом',
'Houses' : 'Дома',
'House_Number' : 'Номер дома',
'House_Building' : 'Строение',
'House_PostalCode' : 'Индекс',
'House_Street' : 'Улица',
'Region' : 'Регион',
'Regions' : 'Регионы',
'Region_Name' : 'Название региона',
'Region_Country' : 'Страна',
'Street' : 'Улица',
'Streets' : 'Улицы',
'Street_Name' : 'Название улицы',
'Street_City' : 'Город',
'Category' : 'Категория',
'Categories' : 'Категории',
'Category_Name' : 'Название категории',
'Category_Description' : 'Описание категории',
'Category_ImagePreview' : 'Изображение категории (превью)',
'Category_ImageFull' : 'Изображение категории',
'Category_ParentCategory' : 'Родительская категория',
'Client' : 'Заказчик',
'Clients' : 'Заказчики',
'Client_Name' : 'Наименование заказчика',
'Client_FullName' : 'Полное наименование заказчика',
'Client_INN' : 'ИНН заказчика',
'Client_OGRN' : 'ОГРН заказчика',
'Client_Location' : 'Адрес заказчика',
'Client_Orders' : 'Заказы',
'Product' : 'Товар',
'Products' : 'Товары',
'Product_Name' : 'Название товара',
'Product_BuyPrice' : 'Цена продажи',
'Product_SellPrice' : 'Цена покупки',
'Product_IsService' : 'Является услугой',
'Product_Category' : 'Категория товара',
'Employee' : 'Сотрудник',
'Employees' : 'Сотрудники',
'Employee_FirstName' : 'Имя',
'Employee_LastName' : 'Фамилия',
'Employee_Patronymic' : 'Отчество',
'Employee_Position' : 'Должность',
'Employee_SNILS' : 'СНИЛС',
'Employee_Email' : 'Email сотрудника',
'Employee_Residence' : 'Место жительства',
'Position' : 'Должность',
'Positions' : 'Должности',
'Position_Name' : 'Название должности'
 }