//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersDb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrdersDb.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of categories.
        /// </summary>
        public static string Amount_Of_Categories {
            get {
                return ResourceManager.GetString("Amount_Of_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of items.
        /// </summary>
        public static string Amount_Of_Items {
            get {
                return ResourceManager.GetString("Amount_Of_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to delete selected record?.
        /// </summary>
        public static string Are_You_Really_Want_ToDelete_Selected_Record {
            get {
                return ResourceManager.GetString("Are_You_Really_Want_ToDelete_Selected_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to delete selected records?.
        /// </summary>
        public static string Are_You_Really_Want_ToDelete_Selected_Records {
            get {
                return ResourceManager.GetString("Are_You_Really_Want_ToDelete_Selected_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories list.
        /// </summary>
        public static string Categories_List {
            get {
                return ResourceManager.GetString("Categories_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category search.
        /// </summary>
        public static string Category_Search {
            get {
                return ResourceManager.GetString("Category_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the product from dropdown.
        /// </summary>
        public static string Choose_The_Product_From_DropDown {
            get {
                return ResourceManager.GetString("Choose_The_Product_From_DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the region from dropdown.
        /// </summary>
        public static string Choose_The_Region_From_DropDown {
            get {
                return ResourceManager.GetString("Choose_The_Region_From_DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list.
        /// </summary>
        public static string Clear_List {
            get {
                return ResourceManager.GetString("Clear_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common order item price.
        /// </summary>
        public static string Common_Order_Item_Price {
            get {
                return ResourceManager.GetString("Common_Order_Item_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create client.
        /// </summary>
        public static string Create_Client {
            get {
                return ResourceManager.GetString("Create_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string Date_Create {
            get {
                return ResourceManager.GetString("Date_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification date.
        /// </summary>
        public static string Date_Modify {
            get {
                return ResourceManager.GetString("Date_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string Delete_Selected {
            get {
                return ResourceManager.GetString("Delete_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed.
        /// </summary>
        public static string Displayed {
            get {
                return ResourceManager.GetString("Displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit city.
        /// </summary>
        public static string Edit_City {
            get {
                return ResourceManager.GetString("Edit_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client.
        /// </summary>
        public static string Edit_Client {
            get {
                return ResourceManager.GetString("Edit_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit order item.
        /// </summary>
        public static string Edit_Order_Item {
            get {
                return ResourceManager.GetString("Edit_Order_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user profile.
        /// </summary>
        public static string Edit_User_Profile {
            get {
                return ResourceManager.GetString("Edit_User_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text.
        /// </summary>
        public static string Enter_The_Text {
            get {
                return ResourceManager.GetString("Enter_The_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag of country.
        /// </summary>
        public static string Flag_Of_Country {
            get {
                return ResourceManager.GetString("Flag_Of_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography.
        /// </summary>
        public static string Geography {
            get {
                return ResourceManager.GetString("Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifers.
        /// </summary>
        public static string Identifers {
            get {
                return ResourceManager.GetString("Identifers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of cities.
        /// </summary>
        public static string List_Of_Cities {
            get {
                return ResourceManager.GetString("List_Of_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        public static string Login_to_your_account {
            get {
                return ResourceManager.GetString("Login_to_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main data.
        /// </summary>
        public static string Main_Data {
            get {
                return ResourceManager.GetString("Main_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of region.
        /// </summary>
        public static string Name_Of_Region {
            get {
                return ResourceManager.GetString("Name_Of_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New city.
        /// </summary>
        public static string New_City {
            get {
                return ResourceManager.GetString("New_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New order item.
        /// </summary>
        public static string New_Order_Item {
            get {
                return ResourceManager.GetString("New_Order_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of numbers comma separated.
        /// </summary>
        public static string Numbers_List_CommaSeparated {
            get {
                return ResourceManager.GetString("Numbers_List_CommaSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order data.
        /// </summary>
        public static string Order_Data {
            get {
                return ResourceManager.GetString("Order_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order items total.
        /// </summary>
        public static string OrderItems_Total {
            get {
                return ResourceManager.GetString("OrderItems_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders creation system.
        /// </summary>
        public static string Orders_Creation_System {
            get {
                return ResourceManager.GetString("Orders_Creation_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Loading Error.
        /// </summary>
        public static string Page_Loading_Error {
            get {
                return ResourceManager.GetString("Page_Loading_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the city.
        /// </summary>
        public static string Please_Choose_The_City {
            get {
                return ResourceManager.GetString("Please_Choose_The_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the country.
        /// </summary>
        public static string Please_Choose_The_Country {
            get {
                return ResourceManager.GetString("Please_Choose_The_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the region.
        /// </summary>
        public static string Please_Choose_The_Region {
            get {
                return ResourceManager.GetString("Please_Choose_The_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the street.
        /// </summary>
        public static string Please_Choose_The_Street {
            get {
                return ResourceManager.GetString("Please_Choose_The_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least three symbols.
        /// </summary>
        public static string Please_Enter_At_Least_Three_Symbols {
            get {
                return ResourceManager.GetString("Please_Enter_At_Least_Three_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least three symbols.
        /// </summary>
        public static string Please_Enter_At_Least_ThreeSymbols {
            get {
                return ResourceManager.GetString("Please_Enter_At_Least_ThreeSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the city name (required).
        /// </summary>
        public static string Please_Enter_The_City_Name_required {
            get {
                return ResourceManager.GetString("Please_Enter_The_City_Name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number.
        /// </summary>
        public static string Please_Enter_The_Number {
            get {
                return ResourceManager.GetString("Please_Enter_The_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population.
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of single product.
        /// </summary>
        public static string Price_Of_Single_Product {
            get {
                return ResourceManager.GetString("Price_Of_Single_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results is empty.
        /// </summary>
        public static string Search_Results_Is_Empty {
            get {
                return ResourceManager.GetString("Search_Results_Is_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are several validation errors.
        /// </summary>
        public static string There_Are_Several_Validation_Errors {
            get {
                return ResourceManager.GetString("There_Are_Several_Validation_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common buy price.
        /// </summary>
        public static string Total_Buy_Price {
            get {
                return ResourceManager.GetString("Total_Buy_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common sell price.
        /// </summary>
        public static string Total_Sell_Price {
            get {
                return ResourceManager.GetString("Total_Sell_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload flag.
        /// </summary>
        public static string Upload_Flag {
            get {
                return ResourceManager.GetString("Upload_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User image.
        /// </summary>
        public static string User_Image {
            get {
                return ResourceManager.GetString("User_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
