//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersDb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntitiesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntitiesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrdersDb.Resources.EntitiesResources", typeof(EntitiesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category description.
        /// </summary>
        public static string Category_Description {
            get {
                return ResourceManager.GetString("Category_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category full image.
        /// </summary>
        public static string Category_ImageFull {
            get {
                return ResourceManager.GetString("Category_ImageFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category preview image.
        /// </summary>
        public static string Category_ImagePreview {
            get {
                return ResourceManager.GetString("Category_ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category parent category.
        /// </summary>
        public static string Category_ParentCategory {
            get {
                return ResourceManager.GetString("Category_ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name.
        /// </summary>
        public static string City_Name {
            get {
                return ResourceManager.GetString("City_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City population.
        /// </summary>
        public static string City_Population {
            get {
                return ResourceManager.GetString("City_Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City region.
        /// </summary>
        public static string City_Region {
            get {
                return ResourceManager.GetString("City_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City streets.
        /// </summary>
        public static string City_Streets {
            get {
                return ResourceManager.GetString("City_Streets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client full name.
        /// </summary>
        public static string Client_FullName {
            get {
                return ResourceManager.GetString("Client_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client INN.
        /// </summary>
        public static string Client_INN {
            get {
                return ResourceManager.GetString("Client_INN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client location.
        /// </summary>
        public static string Client_Location {
            get {
                return ResourceManager.GetString("Client_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name.
        /// </summary>
        public static string Client_Name {
            get {
                return ResourceManager.GetString("Client_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client OGRN.
        /// </summary>
        public static string Client_OGRN {
            get {
                return ResourceManager.GetString("Client_OGRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client orders.
        /// </summary>
        public static string Client_Orders {
            get {
                return ResourceManager.GetString("Client_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        public static string Country_Code {
            get {
                return ResourceManager.GetString("Country_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country flag.
        /// </summary>
        public static string Country_Flag {
            get {
                return ResourceManager.GetString("Country_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name.
        /// </summary>
        public static string Country_Name {
            get {
                return ResourceManager.GetString("Country_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country russian name.
        /// </summary>
        public static string Country_RussianName {
            get {
                return ResourceManager.GetString("Country_RussianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee email.
        /// </summary>
        public static string Employee_Email {
            get {
                return ResourceManager.GetString("Employee_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee first name.
        /// </summary>
        public static string Employee_FirstName {
            get {
                return ResourceManager.GetString("Employee_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee last name.
        /// </summary>
        public static string Employee_LastName {
            get {
                return ResourceManager.GetString("Employee_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee patronymic.
        /// </summary>
        public static string Employee_Patronymic {
            get {
                return ResourceManager.GetString("Employee_Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee position.
        /// </summary>
        public static string Employee_Position {
            get {
                return ResourceManager.GetString("Employee_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee residence.
        /// </summary>
        public static string Employee_Residence {
            get {
                return ResourceManager.GetString("Employee_Residence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee SNILS.
        /// </summary>
        public static string Employee_SNILS {
            get {
                return ResourceManager.GetString("Employee_SNILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House building.
        /// </summary>
        public static string House_Building {
            get {
                return ResourceManager.GetString("House_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number.
        /// </summary>
        public static string House_Number {
            get {
                return ResourceManager.GetString("House_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House postal code.
        /// </summary>
        public static string House_PostalCode {
            get {
                return ResourceManager.GetString("House_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House street.
        /// </summary>
        public static string House_Street {
            get {
                return ResourceManager.GetString("House_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houses.
        /// </summary>
        public static string Houses {
            get {
                return ResourceManager.GetString("Houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order buy price.
        /// </summary>
        public static string Order_BuyPrice {
            get {
                return ResourceManager.GetString("Order_BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order client.
        /// </summary>
        public static string Order_Client {
            get {
                return ResourceManager.GetString("Order_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order code.
        /// </summary>
        public static string Order_Code {
            get {
                return ResourceManager.GetString("Order_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order items.
        /// </summary>
        public static string Order_OrderItems {
            get {
                return ResourceManager.GetString("Order_OrderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sell price.
        /// </summary>
        public static string Order_SellPrice {
            get {
                return ResourceManager.GetString("Order_SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item.
        /// </summary>
        public static string OrderItem {
            get {
                return ResourceManager.GetString("OrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item amount.
        /// </summary>
        public static string OrderItem_Amount {
            get {
                return ResourceManager.GetString("OrderItem_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item buy price.
        /// </summary>
        public static string OrderItem_BuyPrice {
            get {
                return ResourceManager.GetString("OrderItem_BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item order.
        /// </summary>
        public static string OrderItem_Order {
            get {
                return ResourceManager.GetString("OrderItem_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item product.
        /// </summary>
        public static string OrderItem_Product {
            get {
                return ResourceManager.GetString("OrderItem_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item sell price.
        /// </summary>
        public static string OrderItem_SellPrice {
            get {
                return ResourceManager.GetString("OrderItem_SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order items.
        /// </summary>
        public static string OrderItems {
            get {
                return ResourceManager.GetString("OrderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position name.
        /// </summary>
        public static string Position_Name {
            get {
                return ResourceManager.GetString("Position_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product buy price.
        /// </summary>
        public static string Product_BuyPrice {
            get {
                return ResourceManager.GetString("Product_BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category.
        /// </summary>
        public static string Product_Category {
            get {
                return ResourceManager.GetString("Product_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is price.
        /// </summary>
        public static string Product_IsService {
            get {
                return ResourceManager.GetString("Product_IsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product sell price.
        /// </summary>
        public static string Product_SellPrice {
            get {
                return ResourceManager.GetString("Product_SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region country.
        /// </summary>
        public static string Region_Country {
            get {
                return ResourceManager.GetString("Region_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region name.
        /// </summary>
        public static string Region_Name {
            get {
                return ResourceManager.GetString("Region_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string Role_Name {
            get {
                return ResourceManager.GetString("Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role permissions.
        /// </summary>
        public static string Role_Permissions {
            get {
                return ResourceManager.GetString("Role_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role users.
        /// </summary>
        public static string Role_Users {
            get {
                return ResourceManager.GetString("Role_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street city.
        /// </summary>
        public static string Street_City {
            get {
                return ResourceManager.GetString("Street_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name.
        /// </summary>
        public static string Street_Name {
            get {
                return ResourceManager.GetString("Street_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streets.
        /// </summary>
        public static string Streets {
            get {
                return ResourceManager.GetString("Streets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User image.
        /// </summary>
        public static string User_Image {
            get {
                return ResourceManager.GetString("User_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        public static string User_Roles {
            get {
                return ResourceManager.GetString("User_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
