 CommonResources = { 
'Orders' : 'Orders',
'Staff' : 'Staff',
'Geography' : 'Geography',
'Administration' : 'Administration',
'Production' : 'Production',
'Username' : 'Username',
'Password' : 'Password',
'Remember_me' : 'Remember me',
'Login' : 'Login',
'Login_to_your_account' : 'Login to your account',
'Orders_Creation_System' : 'Orders creation system',
'Page_Loading_Error' : 'Page Loading Error',
'Save' : 'Save',
'Actions' : 'Actions',
'User_Image' : 'User image',
'Upload' : 'Upload',
'Edit_User_Profile' : 'Edit user profile',
'Operations' : 'Operations',
'Edit' : 'Edit',
'Del' : 'Del',
'Loading' : 'Loading...',
'Create' : 'Create',
'Delete' : 'Delete',
'Cancel' : 'Cancel',
'Edit_Order_Item' : 'Edit order item',
'New_Order_Item' : 'New order item',
'Price_Of_Single_Product' : 'Price of single product',
'Common_Order_Item_Price' : 'Common order item price',
'Total' : 'Total',
'Displayed' : 'Displayed',
'Selected' : 'Selected',
'There_Are_Several_Validation_Errors' : 'There are several validation errors',
'Add' : 'Add',
'Category_Search' : 'Category search',
'Description' : 'Description',
'Image' : 'Image',
'Information' : 'Information',
'Clear' : 'Clear',
'Date_Create' : 'Creation date',
'Date_Modify' : 'Modification date',
'Amount_Of_Categories' : 'Amount of categories',
'Amount_Of_Items' : 'Amount of items',
'Search_Results_Is_Empty' : 'Search results is empty',
'Search' : 'Search',
'Main_Data' : 'Main data',
'Location' : 'Location',
'Flag_Of_Country' : 'Flag of country',
'Upload_Flag' : 'Upload flag',
'Delete_Selected' : 'Delete selected',
'Clear_List' : 'Clear list',
'Order_Data' : 'Order data',
'OrderItems_Total' : 'Order items total',
'Total_Buy_Price' : 'Common buy price',
'Total_Sell_Price' : 'Common sell price',
'Please_Choose_The_City' : 'Please choose the city',
'Please_Choose_The_Country' : 'Please choose the country',
'Please_Choose_The_Region' : 'Please choose the region',
'Please_Choose_The_Street' : 'Please choose the street',
'Please_Enter_The_Number' : 'Please enter the number',
'Numbers_List_CommaSeparated' : 'List of numbers comma separated',
'Min' : 'Min',
'Max' : 'Max',
'Enter_The_Text' : 'Enter the text',
'Choose_The_Product_From_DropDown' : 'Choose the product from dropdown',
'Amount' : 'Amount',
'Login_Error' : 'Login error',
'Identifers' : 'Identifers',
'Are_You_Really_Want_ToDelete_Selected_Record' : 'Are you really want to delete selected record?',
'Are_You_Really_Want_ToDelete_Selected_Records' : 'Are you really want to delete selected records?',
'Name' : 'Name',
'Please_Enter_At_Least_ThreeSymbols' : 'Please enter at least three symbols',
'Categories_List' : 'Categories list',
'Edit_City' : 'Edit city',
'New_City' : 'New city',
'Choose_The_Region_From_DropDown' : 'Choose the region from dropdown',
'Please_Enter_The_City_Name_required' : 'Please enter the city name (required)',
'Population' : 'Population',
'Name_Of_Region' : 'Name of region',
'Please_Enter_At_Least_Three_Symbols' : 'Please enter at least three symbols',
'List_Of_Cities' : 'List of cities',
'Create_Client' : 'Create client',
'Edit_Client' : 'Edit client'
 }