 EntitiesResources = { 
'Order' : 'Order',
'Orders' : 'Orders',
'Order_Code' : 'Order code',
'Order_OrderItems' : 'Order items',
'Order_Client' : 'Order client',
'Order_SellPrice' : 'Order sell price',
'Order_BuyPrice' : 'Order buy price',
'OrderItem' : 'Order item',
'OrderItems' : 'Order items',
'OrderItem_Product' : 'Order item product',
'OrderItem_Order' : 'Order item order',
'OrderItem_SellPrice' : 'Order item sell price',
'OrderItem_BuyPrice' : 'Order item buy price',
'OrderItem_Amount' : 'Order item amount',
'Role' : 'Role',
'Roles' : 'Roles',
'Role_Name' : 'Role name',
'Role_Users' : 'Role users',
'Role_Permissions' : 'Role permissions',
'User' : 'User',
'Users' : 'Users',
'User_Image' : 'User image',
'User_Name' : 'User name',
'User_Email' : 'User email',
'User_Password' : 'User password',
'User_Roles' : 'User roles',
'City' : 'City',
'Cities' : 'Cities',
'City_Name' : 'City name',
'City_Region' : 'City region',
'City_Population' : 'City population',
'City_Streets' : 'City streets',
'Country' : 'Country',
'Countries' : 'Countries',
'Country_Code' : 'Country code',
'Country_Name' : 'Country name',
'Country_RussianName' : 'Country russian name',
'Country_Flag' : 'Country flag',
'House' : 'House',
'Houses' : 'Houses',
'House_Number' : 'House number',
'House_Building' : 'House building',
'House_PostalCode' : 'House postal code',
'House_Street' : 'House street',
'Region' : 'Region',
'Regions' : 'Regions',
'Region_Name' : 'Region name',
'Region_Country' : 'Region country',
'Street' : 'Street',
'Streets' : 'Streets',
'Street_Name' : 'Street name',
'Street_City' : 'Street city',
'Category' : 'Category',
'Categories' : 'Categories',
'Category_Name' : 'Category name',
'Category_Description' : 'Category description',
'Category_ImagePreview' : 'Category preview image',
'Category_ImageFull' : 'Category full image',
'Category_ParentCategory' : 'Category parent category',
'Client' : 'Client',
'Clients' : 'Clients',
'Client_Name' : 'Client name',
'Client_FullName' : 'Client full name',
'Client_INN' : 'Client INN',
'Client_OGRN' : 'Client OGRN',
'Client_Location' : 'Client location',
'Client_Orders' : 'Client orders',
'Product' : 'Product',
'Products' : 'Products',
'Product_Name' : 'Product name',
'Product_BuyPrice' : 'Product buy price',
'Product_SellPrice' : 'Product sell price',
'Product_IsService' : 'Product is price',
'Product_Category' : 'Product category',
'Employee' : 'Employee',
'Employees' : 'Employees',
'Employee_FirstName' : 'Employee first name',
'Employee_LastName' : 'Employee last name',
'Employee_Patronymic' : 'Employee patronymic',
'Employee_Position' : 'Employee position',
'Employee_SNILS' : 'Employee SNILS',
'Employee_Email' : 'Employee email',
'Employee_Residence' : 'Employee residence',
'Position' : 'Position',
'Positions' : 'Positions',
'Position_Name' : 'Position name'
 }